#!/bin/bash

echo "========================================="
echo "Deploying BGP eBGP Basics Lab"
echo "========================================="
echo ""

# Deploy containerlab topology
echo "Starting containerlab deployment..."
sudo containerlab deploy -t topology.clab.yml

echo ""
echo "========================================="
echo "Lab Deployed Successfully!"
echo "========================================="
echo ""
echo "Topology: AS 100 (r1, r4) <-> AS 200 (r2) <-> AS 300 (r3)"
echo ""
echo "SSH Access (Recommended):"
echo "  ssh -p 2211 admin@localhost  # r1 (AS 100)"
echo "  ssh -p 2212 admin@localhost  # r2 (AS 200)"
echo "  ssh -p 2213 admin@localhost  # r3 (AS 300)"
echo "  ssh -p 2214 admin@localhost  # r4 (AS 100)"
echo "  Password: cisco"
echo ""
echo "Alternative - Docker exec:"
echo "  docker exec -it clab-bgp-ebgp-basics-r1 vtysh"
echo "  docker exec -it clab-bgp-ebgp-basics-r2 vtysh"
echo ""
echo "Run validation:"
echo "  ./scripts/validate.sh"
echo ""
echo "Cleanup:"
echo "  ./scripts/cleanup.sh"
echo ""
